less caching

diff --git a/.github/workflows/next-js.yml b/.github/workflows/next-js.yml
--- a/.github/workflows/next-js.yml
+++ b/.github/workflows/next-js.yml
@@ -52,11 +52,11 @@ jobs:
         run: npm ci
       - name: Build application
         run: npm run build
-      - name: cache workspace
-        uses: actions/cache@v4
+      - name: Upload .next/static for later jobs
+        uses: actions/upload-artifact@v4
         with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+          name: next-static
+          path: .next/static
 
   cypress:
     needs: build-and-publish
@@ -67,11 +67,7 @@ jobs:
       matrix:
         containers: [ 0, 1, 2, 3 ]
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+      - uses: actions/checkout@v4
       - name: cache cypress binary
         uses: actions/cache@v4
         with:
@@ -111,11 +107,12 @@ jobs:
     needs: build-and-publish
     runs-on: ubuntu-latest
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
+      - name: Download static files
+        uses: actions/download-artifact@v4
         with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+          name: next-static
+          path: .next/static
+      - run: ls -R .next/static || echo "Missing .next/static!"
       - name: Last opp static files til NAV CDN
         if: github.ref_name == 'main' || startsWith(github.ref_name, 'dev-')  || startsWith(github.ref_name, 'demo-')
         uses: nais/deploy/actions/cdn-upload/v2@master
@@ -138,11 +135,7 @@ jobs:
     outputs:
       image: ${{ steps.docker-build-push.outputs.image }}
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+      - uses: actions/checkout@v4
       - name: prune dev dependencies
         run: npm prune --production
       - run: rm .env
@@ -162,11 +155,15 @@ jobs:
     needs: build-and-publish
     runs-on: ubuntu-latest
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+          node-version: 20
+          cache: 'npm'
+      - name: Install npm dependencies
+        env:
+          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: npm ci
       - name: Run prettier
         run: npm run prettier:check
       - name: Run lint
@@ -178,11 +175,15 @@ jobs:
     needs: build-and-publish
     runs-on: ubuntu-latest
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
         with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+          node-version: 20
+          cache: 'npm'
+      - name: Install npm dependencies
+        env:
+          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: npm ci
       - name: Run tests
         run: npm run test:ci
 
@@ -271,11 +272,7 @@ jobs:
       IMAGE_NAME: ${{ github.repository }}-e2e
       REGISTRY: ghcr.io
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+      - uses: actions/checkout@v4
       - name: Log in to the Container registry
         uses: docker/login-action@v3
         with:
@@ -304,11 +301,7 @@ jobs:
         shardIndex: [1, 2, 3, 4]
         shardTotal: [4]
     steps:
-      - name: cache workspace
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}
-          key: ${{ github.sha }}
+      - uses: actions/checkout@v4
       - name: Install Playwright browsers
         run: npx playwright install
       - name: Run Playwright
